name: "Bump package version"

on:
  push:
    branches: ["master", "main"]

permissions:
  contents: write

jobs:
  bump-package-version:
    name: Bump package version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check bump type
        run: |
          echo BUMP=$(echo ${{ github.event.head_commit.message }} \
          | grep -o "bump:\(major\|minor\|patch\)" \
          | grep -o "major\|minor\|patch") >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Bump version
        if: ${{ env.BUMP == 'major' || env.BUMP == 'minor' || env.BUMP == 'patch' }}
        run: |
          npm version ${{ env.BUMP }}

      - name: Push version change
        if: ${{ env.BUMP == 'major' || env.BUMP == 'minor' || env.BUMP == 'patch' }}
        run: |
          git config --global user.name '[Auto] Ricardo Rocha'
          git config --global user.email 'ricdotnet@users.noreply.github.com'
          git push

      - name: Enable corepack
        if: ${{ env.BUMP == 'major' || env.BUMP == 'minor' || env.BUMP == 'patch' }}
        run: corepack enable

      - name: Build package
        if: ${{ env.BUMP == 'major' || env.BUMP == 'minor' || env.BUMP == 'patch' }}
        run: |
          yarn install
          yarn build

      - name: Publish to npm
        if: ${{ env.BUMP == 'major' || env.BUMP == 'minor' || env.BUMP == 'patch' }}
        run: echo "Publishing to npm"
