name: "Code Quality Checks"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  code-checks:
    runs-on: ubuntu-latest
    name: Run linting and tests
    steps:
      - id: code-checks
        uses: ricdotnet-org/js-code-checks@alpha_1
        with:
          package-manager: 'yarn'